#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd)
export DOTFILES_SCRATCH=$DOTFILES_ROOT/__dotfiles_scratch__

set -e

source $DOTFILES_ROOT/bootstrap/functions

echo ''

log_info "Running installers"
run_installer "preinstall.sh"

log_info "Linking dotfiles"
link_dotfiles

log_info "Cloning repos"
clone_repos

log_info "Running installers"
run_installer "install.sh"

log_info "Running postinstallers"
run_installer "postinstall.sh"

echo ''
log_success '  All installed!'
