#!/usr/bin/env bash
#
# bootstrap installs things.

set -e

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
DOTFILES_SCRATCH="${DOTFILES_ROOT}/__dotfiles_scratch__"

export DOTFILES_ROOT
export DOTFILES_SCRATCH

source "${DOTFILES_ROOT}/bootstrap/functions"

echo ''

log_info "Running installers"
run_installer "preinstall.sh"

log_info "Linking dotfiles"
link_dotfiles

log_info "Cloning repos"
clone_repos

log_info "Running installers"
run_installer "install.sh"

log_info "Running postinstallers"
run_installer "postinstall.sh"

echo ''
log_success '  All installed!'
