#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd)
export DOTFILES_SCRATCH=$DOTFILES_ROOT/__dotfiles_scratch__

set -e

source $DOTFILES_ROOT/bootstrap/functions

echo ''

info "Running installers"
run_installer "preinstall.sh"

info "Linking dotfiles"
link_dotfiles

info "Cloning repos"
clone_repos

info "Running installers"
run_installer "install.sh"

info "Running postinstallers"
run_installer "postinstall.sh"

echo ''
success '  All installed!'
